### ISSUE TITLE
机器人报错

### ISSUE THREAD

**Issue by yuanzhidao** [ZYKsslm/nonebot_plugin_zyk_novelai#8]
12-10 08:38:51 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_zyk_novelai) running complete
12-10 08:38:51 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_zyk_novelai) failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/python3/lib/python3.11/multiprocessing/spawn.py", line 120, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/python3/lib/python3.11/multiprocessing/spawn.py", line 133, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/local/python3/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/python3/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/python3/lib/python3.11/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/python3/lib/python3.11/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/python3/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/usr/local/python3/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/usr/local/python3/lib/python3.11/site-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/python3/lib/python3.11/site-packages/nonebot/message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/python3/lib/python3.11/site-packages/nonebot/internal/matcher/matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/python3/lib/python3.11/site-packages/nonebot/internal/matcher/matcher.py", line 702, in simple_run
    await handler(
  File "/usr/local/python3/lib/python3.11/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/usr/local/python3/lib/python3.11/site-packages/nonebot_plugin_zyk_novelai/__init__.py", line 189, in _
    data = await get_data(post_url=post_url, size=size, prompt=prompt, proxies=proxies, uc=uc, steps=steps, scale=scale, seed=seed)
NameError: name 'proxies' is not defined

**Comment by yuanzhidao** [comment]
暂时解决 但是是修改env文件修复的
机器人指令设置后端不好使

**Comment by ZYKsslm** [comment]
请问报错时你的env配置是什么呢

**Comment by yuanzhidao** [comment]
env未配置

**Comment by ZYKsslm** [comment]
最新版已修复BUG
